### PR TITLE
Update index.php

### PR DESCRIPTION
**Pull request by jweaver0312**

### CODE REVIEW

**Comment by LeonetKenner** [comment]
Can ya do it without the body tag

**Comment by jweaver0312** [comment]
works without the body tags, I was just in a HTML mode at the moment.

**Comment by LeonetKenner** [comment]
I kinda want to add this to Dev branch since ik we can do without html

**Comment by LeonetKenner** [comment]
Can you kinda make anpull request to the Dev branch instead?

**Comment by jweaver0312** [comment]
I have an alternative solution, but the only thing I could not avoid was the <!doctype html> at the top. Safari and Chrome went crazy without it. I'm not seeing a dev branch to make the pull to, but I'll make a new pull for the alternative solution.

I see it now, ill move this into the dev branch.

**Pull request closed without merging**
